#!/bin/bash

if [ x"$WARPDRIVE_DEBUG" != x"" ]; then
    set -x
fi

WARPDRIVE_SERVER_ARGS="--log-file - --bind 0.0.0.0:8080"

if [ -f .warpdrive/server_args ]; then
    WARPDRIVE_SERVER_ARGS="$WARPDRIVE_SERVER_ARGS `cat .warpdrive/server_args`"

    # Expand any environment variable references in options.

    WARPDRIVE_TMP_FILE=/tmp/server_args.$$

    cat > $WARPDRIVE_TMP_FILE << EOF
#!/bin/sh
cat << !
$WARPDRIVE_SERVER_ARGS
!
EOF

    chmod +x $WARPDRIVE_TMP_FILE

    WARPDRIVE_SERVER_ARGS=`$WARPDRIVE_TMP_FILE`

    rm -f $WARPDRIVE_TMP_FILE
fi

if [ $$ = 1 ]; then
    WARPDRIVE_TINI="tini --"
fi

echo " -----> Executing server command '$WARPDRIVE_TINI gunicorn $WARPDRIVE_SERVER_ARGS'"

exec $WARPDRIVE_TINI gunicorn $WARPDRIVE_SERVER_ARGS
