#!/bin/bash

WARPDRIVE_VIRTUALENVS=${WARPDRIVE_VIRTUALENVS:-$HOME/.warpdrive}

if [ "$#" = "0" ]; then
    echo "Usage: warpdrive destroy PROJECT"
    exit 1
fi

WARPDRIVE_ENV_NAME="$1"

WARPDRIVE_VENV_DIR="$WARPDRIVE_VIRTUALENVS/warpdrive+$WARPDRIVE_ENV_NAME"

if [ ! -d "$WARPDRIVE_VENV_DIR" ]; then
    echo "The warpdrive project '$WARPDRIVE_ENV_NAME' does not exist."
    exit 1
else
    echo "Destroying warpdrive project '$WARPDRIVE_ENV_NAME'."

    rm -r $WARPDRIVE_VENV_DIR
fi
