#!/bin/bash

# This script will run an interactive bash shell.

# Setup the environment if not already done.

if [ x"$WARPDRIVE_ACTION" = x"" ]; then
    eval "$(warpdrive env)"
fi

WARPDRIVE_ACTION=shell
export WARPDRIVE_ACTION

# Now finally run bash.

exec bash
