#!/bin/bash

if [ x"$WARPDRIVE_DEBUG" != x"" ]; then
    set -x
fi

# This script will trigger installation of Python in base image.

WARPDRIVE_BASE=`which $0`
WARPDRIVE_SCRIPTS=`dirname $WARPDRIVE_BASE`

WARPDRIVE_OSTYPE=$1

echo " -----> Running base image script base-$WARPDRIVE_OSTYPE"

exec $WARPDRIVE_SCRIPTS/base-$WARPDRIVE_OSTYPE
