#!/bin/sh

if [ x"$WARPDRIVE_DEBUG" != x"" ]; then
    set -x
fi

if [ -x /usr/local/s2i/bin/assemble ]; then
    exec /usr/local/s2i/bin/assemble
fi

if [ -x /opt/app-root/s2i/bin/assemble ]; then
    exec /opt/app-root/s2i/bin/assemble
fi

curl -SL -o /opt/app-root/getwarped.sh \
  https://raw.githubusercontent.com/GrahamDumpleton/warpdrive/master/getwarped.sh

WARPDRIVE_VERSION=${WARPDRIVE_VERSION:-0}

if [ x"$WARPDRIVE_DEBUG" != x"" ]; then
    sh -x /opt/app-root/getwarped.sh --version $WARPDRIVE_VERSION
else
    sh /opt/app-root/getwarped.sh --version $WARPDRIVE_VERSION
fi

exec /opt/app-root/s2i/bin/assemble
