#!/bin/bash

if [ x"$WARPDRIVE_DEBUG" != x"" ]; then
    set -x
fi

if [ -x /usr/local/s2i/bin/run ]; then
    WARPDRIVE_S2I_ROOT=/usr/local/s2i
    export WARPDRIVE_S2I_ROOT

    exec /usr/local/s2i/bin/run
fi

WARPDRIVE_S2I_ROOT=/opt/app-root/s2i
export WARPDRIVE_S2I_ROOT

exec /opt/app-root/s2i/bin/run
