#!/bin/sh

if [ x"$WARPDRIVE_DEBUG" != x"" ]; then
    set -x
fi

if [ -x /usr/local/s2i/bin/save-artifacts ]; then
    exec /usr/local/s2i/bin/save-artifacts
fi

exec /opt/app-root/s2i/bin/save-artifacts
